[[redirects]]
from = "/delegazioni-territoriali"
to = "/chi-siamo"
status = 302
force = true

[[redirects]]
from = "/delegazioni-territoriali/"
to = "/chi-siamo"
status = 302
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
